import { lazy } from 'react'

// Helper for lazy loading with a small delay to prevent flickering on fast connections
// and to show off our nice transitions
const lazyWithDelay = (importFn) => lazy(async () => {
  const [moduleExport] = await Promise.all([
    importFn(),
    new Promise(resolve => setTimeout(resolve, 300))
  ])
  return moduleExport
})

export const screens = [
  lazy(() => import('./screens/LandingPage')),
  
  // Module 1
  lazy(() => import('./screens/Module1/Screen1')),
  lazy(() => import('./screens/Module1/Screen2')),
  lazy(() => import('./screens/Module1/Screen3')),
  lazy(() => import('./screens/Module1/Screen4')),
  lazy(() => import('./screens/Module1/Screen5')),
  lazy(() => import('./screens/Module1/Screen6')),
  lazy(() => import('./screens/Module1/Screen7')),
  lazy(() => import('./screens/Module1/Screen8')),
  lazy(() => import('./screens/Module1/Screen9')),
  lazy(() => import('./screens/Module1/Screen10')),

  // Module 2
  lazy(() => import('./screens/Module2/Screen1')),
  lazy(() => import('./screens/Module2/Screen2')),
  lazy(() => import('./screens/Module2/Screen3')),
  lazy(() => import('./screens/Module2/Screen4')),
  lazy(() => import('./screens/Module2/Screen5')),
  lazy(() => import('./screens/Module2/Screen6')),
  lazy(() => import('./screens/Module2/Screen7')),
  lazy(() => import('./screens/Module2/Screen8')),
  lazy(() => import('./screens/Module2/Screen9')),
  lazy(() => import('./screens/Module2/Screen10')),
  lazy(() => import('./screens/Module2/Screen11')),
  lazy(() => import('./screens/Module2/Screen12')),
  lazy(() => import('./screens/Module2/Screen13')),
  lazy(() => import('./screens/Module2/Screen14')),
  lazy(() => import('./screens/Module2/Screen15')),
  lazy(() => import('./screens/Module2/Screen16')),
  lazy(() => import('./screens/Module2/Screen17')),
  lazy(() => import('./screens/Module2/Screen18')),
  lazy(() => import('./screens/Module2/Screen19')),
  lazy(() => import('./screens/Module2/Screen20')),

  // Module 3
  lazy(() => import('./screens/RetrievalScreen').then(m => ({ default: m.M3Retrieval }))),
  lazy(() => import('./screens/Module3/Screen1')),
  lazy(() => import('./screens/Module3/Screen2')),
  lazy(() => import('./screens/Module3/Screen3')),
  lazy(() => import('./screens/Module3/Screen4')),
  lazy(() => import('./screens/Module3/Screen5')),
  lazy(() => import('./screens/Module3/Screen6')),
  lazy(() => import('./screens/Module3/Screen7')),
  lazy(() => import('./screens/Module3/Screen8')),
  lazy(() => import('./screens/Module3/Screen9')),
  lazy(() => import('./screens/Module3/Screen10')),
  lazy(() => import('./screens/Module3/Screen11')),
  lazy(() => import('./screens/Module3/Screen12')),
  lazy(() => import('./screens/Module3/Screen13')),
  lazy(() => import('./screens/Module3/Screen14')),
  lazy(() => import('./screens/Module3/Screen15')),
  lazy(() => import('./screens/Module3/Screen16')),
  lazy(() => import('./screens/Module3/Screen17')),
  lazy(() => import('./screens/Module3/Screen18')),
  lazy(() => import('./screens/Module3/Screen19')),
  lazy(() => import('./screens/Module3/Screen20')),

  // Module 4
  lazy(() => import('./screens/RetrievalScreen').then(m => ({ default: m.M4Retrieval }))),
  lazy(() => import('./screens/Module4/Screen1')),
  lazy(() => import('./screens/Module4/Screen2')),
  lazy(() => import('./screens/Module4/Screen3')),
  lazy(() => import('./screens/Module4/Screen4')),
  lazy(() => import('./screens/Module4/Screen5')),
  lazy(() => import('./screens/Module4/Screen6')),
  lazy(() => import('./screens/Module4/Screen7')),
  lazy(() => import('./screens/Module4/Screen8')),
  lazy(() => import('./screens/Module4/Screen9')),
  lazy(() => import('./screens/Module4/Screen10')),
  lazy(() => import('./screens/Module4/Screen11')),
  lazy(() => import('./screens/Module4/Screen12')),
  lazy(() => import('./screens/Module4/Screen13')),
  lazy(() => import('./screens/Module4/Screen14')),
  lazy(() => import('./screens/Module4/Screen15')),
  lazy(() => import('./screens/Module4/Screen16')),
  lazy(() => import('./screens/Module4/Screen17')),
  lazy(() => import('./screens/Module4/Screen18')),
  lazy(() => import('./screens/Module4/Screen19')),
  lazy(() => import('./screens/Module4/Screen20')),
  lazy(() => import('./screens/Module4/Screen21')),
  lazy(() => import('./screens/Module4/Screen22')),
  lazy(() => import('./screens/Module4/Screen23')),
  lazy(() => import('./screens/Module4/Screen24')),
  lazy(() => import('./screens/Module4/Screen25')),

  // Module 5
  lazy(() => import('./screens/RetrievalScreen').then(m => ({ default: m.M5Retrieval }))),
  lazy(() => import('./screens/Module5/Screen1')),
  lazy(() => import('./screens/Module5/Screen2')),
  lazy(() => import('./screens/Module5/Screen3')),
  lazy(() => import('./screens/Module5/Screen4')),
  lazy(() => import('./screens/Module5/Screen5')),
  lazy(() => import('./screens/Module5/Screen6')),
  lazy(() => import('./screens/Module5/Screen7')),
  lazy(() => import('./screens/Module5/Screen8')),
  lazy(() => import('./screens/Module5/Screen9')),
  lazy(() => import('./screens/Module5/Screen10')),
  lazy(() => import('./screens/Module5/Screen11')),
  lazy(() => import('./screens/Module5/Screen12')),
  lazy(() => import('./screens/Module5/Screen13')),
  lazy(() => import('./screens/Module5/Screen14')),
  lazy(() => import('./screens/Module5/Screen15')),
  lazy(() => import('./screens/Module5/Screen16')),
  lazy(() => import('./screens/Module5/Screen17')),
  lazy(() => import('./screens/Module5/Screen18')),
  lazy(() => import('./screens/Module5/Screen19')),
  lazy(() => import('./screens/Module5/Screen20')),
  lazy(() => import('./screens/Module5/Screen21')),
  lazy(() => import('./screens/Module5/Screen22')),
  lazy(() => import('./screens/Module5/Screen23')),
  lazy(() => import('./screens/Module5/Screen24')),
  lazy(() => import('./screens/Module5/Screen25')),
  lazy(() => import('./screens/Module5/Screen26')),
  lazy(() => import('./screens/Module5/Screen27')),
  lazy(() => import('./screens/Module5/Screen28')),
  lazy(() => import('./screens/Module5/Screen29')),
  lazy(() => import('./screens/Module5/Screen30')),

  // Module 6
  lazy(() => import('./screens/RetrievalScreen').then(m => ({ default: m.M6Retrieval }))),
  lazy(() => import('./screens/Module6/Screen1')),
  lazy(() => import('./screens/Module6/Screen2')),
  lazy(() => import('./screens/Module6/Screen3')),
  lazy(() => import('./screens/Module6/Screen4')),
  lazy(() => import('./screens/Module6/Screen5')),
  lazy(() => import('./screens/Module6/Screen6')),
  lazy(() => import('./screens/Module6/Screen7')),
  lazy(() => import('./screens/Module6/Screen8')),
  lazy(() => import('./screens/Module6/Screen9')),
  lazy(() => import('./screens/Module6/Screen10')),
  lazy(() => import('./screens/Module6/Screen11')),
  lazy(() => import('./screens/Module6/Screen12')),
  lazy(() => import('./screens/Module6/Screen13')),
  lazy(() => import('./screens/Module6/Screen14')),
  lazy(() => import('./screens/Module6/Screen15')),
  lazy(() => import('./screens/Module6/Screen16')),
  lazy(() => import('./screens/Module6/Screen17')),
  lazy(() => import('./screens/Module6/Screen18')),
  lazy(() => import('./screens/Module6/Screen19')),
  lazy(() => import('./screens/Module6/Screen20')),
  lazy(() => import('./screens/Module6/Screen21')),
  lazy(() => import('./screens/Module6/Screen22')),
  lazy(() => import('./screens/Module6/Screen23')),
  lazy(() => import('./screens/Module6/Screen24')),

  // Post Course
  lazy(() => import('./screens/PostCourse/Screen1')),
  lazy(() => import('./screens/PostCourse/Screen2')),
  lazy(() => import('./screens/PostCourse/Screen3')),
  lazy(() => import('./screens/PostCourse/Screen4')),
  lazy(() => import('./screens/PostCourse/Screen5')),
  lazy(() => import('./screens/PostCourse/Screen6')),
]

export const moduleDefinitions = [
  { id: 1, title: "What Constraints Do", start: 1, end: 10 },
  { id: 2, title: "Start With the Problem", start: 11, end: 30 },
  { id: 3, title: "Notice Targets", start: 31, end: 51 },
  { id: 4, title: "Constraint Levers", start: 52, end: 77 },
  { id: 5, title: "Build the Upgrade", start: 78, end: 108 },
  { id: 6, title: "Observation & Adjustment", start: 109, end: 133 },
  { id: 'Final', title: "Wrap-Up & Challenge", start: 134, end: 139 },
]
